spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    driver-class-name: "org.h2.Driver"
    username: sa
    password:
    url: "jdbc:h2:file:~sb-h2-db"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
jwt:
  secret: "UPDATE THIS SHIT"
