spring:
profiles:
  active: dev
  # DB config
  datasource:
    url: jdbc:h2:mem:backfusion
    driverClassName: org.h2.Driver
    username: admin
    password: admin
# JPA config
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
# Logging config
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: TRACE
# JWT config
jwt:
  secret: "T2i8xH5hK+pjXK2Wm7/L1g7Y3Y+3mG52qZsFzr8cH2QIB3cQ5uWVQmtiNl+3Zc2lq8yQV/7o+y0G1CxFuUjFb5N6RQ=="
  exp-time: 1800 # 30 * 60 => 30min
