spring:
profiles:
  active: dev
  # DB config
  datasource:
    url: jdbc:h2:mem:backfusion
    driverClassName: org.h2.Driver
    username: admin
    password: admin
# JPA config
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
# Logging config
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: TRACE
# JWT config
jwt:
  secret: "UPDATE THIS SHIT"
